name: Taking snapshot of the Alcumus website
on: [workflow_dispatch]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run snapshot
        run: |
          python main.py
      - name: Updating data.json
        uses: EndBug/add-and-commit@v7
        with:
          author_name: snapshot_action
          message: 'Latest snapshot'
          add: 'docs/data.json'
